### ISSUE TITLE
Secret Provider for Docker secrets

### ISSUE THREAD

**Issue by fgheysels** [arcus-azure/arcus.security#149]
I think separating secrets from configuration is very valuable, and I was thinking if it would make sense to create a provider which can be used for Docker secrets.

**What secret store are you interested in?**
A secret store provider which allows to access docker secrets that are made available to a container.

**What scenarios would it enable you?**
It would enable me to treat docker secrets as secrets (and not as configuration values) in a docker container stack.

**More information**
There exists a Configuration Provider which makes docker secrets available in the configuration.
When giving a container access to a secret, the secret gets 'injected' as a file in the container.  The [KeyPerFileConfigurationProvider](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.configuration.keyperfile.keyperfileconfigurationprovider?view=dotnet-plat-ext-3.1) allows to make those files available in the configuration, however, since those things are actually secrets, it would make sense to create a Secret Provider for it.

Suppose you have a docker compose file which contains this:

```yaml
services:
  foo-service:
    image: localhost:5000/foo-service
    secrets:
      ConnectionStrings__FooDatabase

secrets:
  ConnectionStrings__FooDatabase:
    external: true
```

When running the container, a file will be injected in a certain location (the location depends whether you're targetting Linux or Windows containers) and that file will contain the secret.   It would be nice if there was a provider which is similar as the `KeyPerFileConfigurationProvider` which adds those files in the Secret Store.
```
