### ISSUE TITLE
How to distinguish secrets and configuration values when using K8s

### ISSUE THREAD

**Issue by fgheysels** [arcus-azure/arcus.security#160]
**Description**
`ISecretStore` allows us to have a clear and explicit distinction between secrets and configuration values.  

This is a good thing, but I'm wondering how to do this when using containerized applications that run in Kubernetes.   I'm totally not a K8s expert but AFAIK, when using K8s, you typically bind secrets to environment variables.

How can we make a distinction between environment variables that are a secret, and environment variables that are a regular config value ?
I think that the distinction between secrets & configuration is somewhat blurred in this case ?

**Comment by tomkerkhove** [comment]
It depends on what secret store you are using and how you want to read them but even if they are loaded as environment variables you can just consume them; that's infrastructure details.

Your app will say, give me `DB-ConnectionString` and it will fetch it from environment variables for you given that's how you've configured it. Your secret store configuration has to be designed around how it will be run. 

That is for example why I never use configuration files and only use environment variables as this is more widely used.

**Comment by fgheysels** [comment]
My concern is rather, given this set of environment variables for a kubernetes service for instanc:e
```yaml
- env:
        - name: Services__LocationServiceUrl
          value: http://locations-api:80
        - name: ConnectionStrings__Database
          valueFrom:
            secretKeyRef:
              name: my-secrets
              key: ConnectionStrings__DB
```
That the Configuration Provider gives you access to both config values and secrets, and the SecretProvider gives you access to config & secrets as well.
